"""Static PEP 503 ``/simple/`` emitter + the pip-resolvability ``_redirects``.

Pure string builders — no I/O, no deps — so they unit-test cleanly. Ported from
``../auntiepypi``'s index logic (PEP 503 name normalization + the root HTML),
adapted to emit *static* files at build time rather than serve them from a
running ``http.server``.

The index does not host wheels. To make ``/simple/`` **pip-resolvable** without
hosting files, each certified tool's ``/simple/<name>/`` is a Cloudflare
``_redirects`` rule pointing at the tool's real PyPI simple page. Only listed
tools get a rule, so the index stays curated — ``pip install --index-url
https://tools.culture.dev/simple/ <tool>`` resolves a certified tool's files from
PyPI, and anything uncertified falls through to 404. There is deliberately **no
static page** at ``/simple/<name>/``: a static asset would shadow the redirect
(Cloudflare applies ``_redirects`` only after an exact static-asset miss).
"""

from __future__ import annotations

import html
import re

_NORMALIZE_RE = re.compile(r"[-_.]+")
_PYPI_SIMPLE = "https://pypi.org/simple"


def normalize(name: str) -> str:
    """PEP 503 normalized project name: lowercase, runs of ``[-_.]`` → single ``-``."""
    return _NORMALIZE_RE.sub("-", name).lower()


def render_root(project_names: list[str]) -> str:
    """The ``/simple/index.html`` root: one anchor per project, sorted, normalized."""
    rows = [
        f'    <a href="{normalize(name)}/">{html.escape(name)}</a><br/>'
        for name in sorted(project_names, key=normalize)
    ]
    body = "\n".join(rows) if rows else "    <!-- no conformant tools -->"
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "  <head>\n"
        '    <meta charset="utf-8" />\n'
        '    <meta name="pypi:repository-version" content="1.0" />\n'
        "    <title>Simple index — tools.culture.dev</title>\n"
        "  </head>\n"
        "  <body>\n"
        f"{body}\n"
        "  </body>\n"
        "</html>\n"
    )


def render_redirects(project_names: list[str]) -> str:
    """The Cloudflare ``_redirects`` file making ``/simple/`` pip-resolvable.

    One rule per certified tool, mapping ``/simple/<name>/`` (and the
    trailing-slash-less form pip may also request) to the tool's PyPI simple page.
    Sorted + normalized; only listed tools resolve.
    """
    lines = [
        "# Generated by `culture-tools index build` — do not edit by hand.",
        "# pip-resolvable /simple/: each AgentFront-certified tool redirects to its",
        "# PyPI simple page (the real distribution files). Only listed tools resolve,",
        "# so the index stays curated; uncertified names fall through to 404.",
    ]
    for name in sorted(project_names, key=normalize):
        norm = normalize(name)
        target = f"{_PYPI_SIMPLE}/{norm}/"
        lines.append(f"/simple/{norm}/   {target}   302")
        lines.append(f"/simple/{norm}    {target}   302")
    lines.append("")
    return "\n".join(lines)
